# TUM FR3/Office 数据集混合SLAM配置
inherit_from: "configs/base/hybrid_base.yaml"

# 继承MonoGS原始配置
MonoGS:
  inherit_from: "thirdparty/MonoGS/configs/mono/tum/fr3_office.yaml"

# 数据集特定配置
Dataset:
  type: 'tum'
  sensor_type: 'monocular'  
  dataset_path: "thirdparty/MonoGS/datasets/tum/rgbd_dataset_freiburg3_long_office_household"

# 针对fr3_office的优化配置
EfficientLoFTR:
  model_path: "thirdparty/EfficientLoFTR/weights/indoor_ds.ckpt"  # 室内模型
  confidence_threshold: 0.18           # 办公室场景纹理丰富

PnPSolver:
  ransac_threshold: 2.0                # 标准阈值
  min_inliers: 25                      # 办公室特征丰富，提高要求

HybridTracking:
  feature_matching_interval: 1         # 办公室场景每帧匹配
  fallback_threshold: 3                # 降低失败阈值

# 结果配置
Results:
  save_results: true
  save_dir: "results/hybrid_slam/tum_fr3_office"
  use_gui: true
  eval_rendering: true