# EfficientLoFTR Outdoor Model Configuration
# 户外场景特化配置

inherit_from: '../base/hybrid_slam_base.yaml'

# EfficientLoFTR outdoor-specific settings
EfficientLoFTR:
  model_path: 'models/eloftr_outdoor.ckpt'
  confidence_threshold: 0.25  # Higher threshold for outdoor
  max_matches: 3000
  
  # Outdoor-specific preprocessing
  image_preprocessing:
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Adjusted tracking for outdoor scenes
HybridTracking:
  min_matches: 80  # More matches needed for outdoor
  min_inliers: 30
  feature_confidence: 0.25
  
  # More conservative keyframe selection for outdoor
  keyframe_translation_threshold: 0.2
  keyframe_rotation_threshold: 0.1

PnPSolver:
  pnp_ransac_threshold: 3.0  # Looser threshold for outdoor noise
  pnp_max_iterations: 2000
  pnp_min_inliers: 30

# Performance optimizations for outdoor scenes
performance:
  enable_profiling: true
  memory_monitoring: true