# EfficientLoFTR 户外模型配置

EfficientLoFTR:
  model_type: "opt"
  precision: "fp32"
  
  # 模型路径
  model_path: "thirdparty/EfficientLoFTR/weights/eloftr_outdoor.ckpt"
  
  # 户外场景优化参数
  confidence_threshold: 0.2
  max_keypoints: 2000
  
  # 模型配置
  config:
    backbone_type: 'RepVGG'
    resolution: [8, 1]
    fine_window_size: 8
    
    coarse:
      d_model: 256
      d_ffn: 256
      nhead: 8
      layer_names: ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross']
      
    match_coarse:
      thr: 0.2
      border_rm: 2