# EfficientLoFTR 室内模型配置

EfficientLoFTR:
  model_type: "opt" 
  precision: "fp32"
  
  # 模型路径
  model_path: "thirdparty/EfficientLoFTR/weights/indoor_ds.ckpt"
  
  # 室内场景优化参数
  confidence_threshold: 0.15           # 室内降低阈值
  max_keypoints: 1500                  # 室内特征通常较少
  
  # 室内特有配置
  enable_local_feature_refinement: true
  local_refinement_radius: 3
  
  # 模型配置 (室内优化)
  config:
    backbone_type: 'RepVGG'
    resolution: [8, 1]
    fine_window_size: 8
    
    coarse:
      d_model: 256
      d_ffn: 256  
      nhead: 8
      
    match_coarse:
      thr: 0.15                        # 室内降低匹配阈值
      border_rm: 2