# Hybrid SLAM with MonoGS Configuration
device: 'cuda'

# Input configuration
input:
  source: 'camera'  # or 'mock' for testing
  camera:
    left_device: 0
    right_device: 1
    resolution: [640, 480]
    fps: 20
    calibration_file: null  # Will use default calibration

# Frontend configuration (EfficientLoFTR + PnP)
frontend:
  matcher_type: 'loftr'
  tracking_method: 'hybrid'  # feature + rendering
  min_matches: 50
  min_inliers: 20
  feature_confidence: 0.2
  tracking_lost_threshold: 10

# EfficientLoFTR configuration
EfficientLoFTR:
  model_path: 'thirdparty/EfficientLoFTR/weights/eloftr_outdoor.ckpt'
  resize_to: [640, 480]
  match_threshold: 0.2
  max_keypoints: 2048

# PnP Solver configuration  
PnPSolver:
  method: 'EPNP'
  ransac_threshold: 3.0
  max_iterations: 1000
  confidence: 0.999

# MonoGS backend configuration
monogs:
  # Dataset configuration
  Dataset:
    type: "custom"
    sensor_type: "stereo"  # Change to "monocular" if using single camera
    
  # Model parameters
  model_params:
    sh_degree: 3
    source_path: ""
    model_path: ""
    resolution: -1
    white_background: false
    data_device: "cuda"
    eval: false

  # Optimization parameters
  opt_params:
    iterations: 30000
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.005
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002

  # Pipeline parameters
  pipeline_params:
    convert_SHs_python: false
    compute_cov3D_python: false
    debug: false

  # Training configuration
  Training:
    spherical_harmonics: true
    tracking_itr_num: 40
    mapping_itr_num: 60
    gaussian_th: 0.5
    size_threshold: 20
    window_size: 24
    single_thread: false
    
    # Learning rates
    lr:
      cam_rot_delta: 0.004
      cam_trans_delta: 0.002
      
    # Keyframe selection
    kf_translation: 0.4
    kf_min_translation: 0.1  
    kf_overlap: 0.45

  # Results configuration
  Results:
    use_gui: false  # Set to true for GUI
    eval_rendering: false
    save_results: true
    save_trj: true
    save_trj_kitti_fmt: false

# MonoGS adapter (fallback when MonoGS not available)
monogs_adapter:
  save_intermediate: true
  max_frames: 1000

# Performance targets
performance_targets:
  target_fps: 15
  max_memory_gb: 16
  max_gpu_memory_gb: 8

# Visualization
visualization: true
visualization_config:
  save_mode: true
  save_dir: 'hybrid_monogs_visualization'
  save_frequency: 5
  window_size: [1400, 800]
  show_trajectory: true
  show_pointcloud: true

# Output configuration
output:
  save_trajectory: true
  save_keyframes: true
  save_pointcloud: true
  formats:
    trajectory: ['tum', 'kitti']
    pointcloud: ['ply', 'pcd']