# 测试配置 - 使用模拟数据测试系统
# Test Configuration - Mock data for system testing

project_name: 'Hybrid SLAM Test'
version: '1.0.0'
description: 'Test configuration with mock data'

# 基本设置
mode: 'slam'
real_time: true
visualization: true
device: 'cuda'

# 使用模拟数据源（不需要真实摄像头）
input:
  source: 'mock'  # 使用模拟数据
  
  camera:
    left_device: 0
    right_device: 1
    resolution: [640, 480]
    fps: 30
    calibration_file: null

# 输出设置
output:
  save_trajectory: true
  save_pointcloud: false
  save_mesh: false
  save_video: false
  save_metrics: true
  save_keyframes: false
  
  formats:
    trajectory: ['tum']

# 前端配置（简化）
frontend:
  device: 'cuda'
  min_matches: 10  # 降低要求用于测试
  min_inliers: 8
  feature_confidence: 0.1
  tracking_lost_threshold: 20

# EfficientLoFTR配置（简化）
EfficientLoFTR:
  model_path: null  # 测试时不加载模型
  resize_to: [640, 480]
  match_threshold: 0.1
  max_keypoints: 1000
  enable_stereo_constraints: false  # 简化测试

# PnP求解器配置（简化）
PnPSolver:
  pnp_method: 'SOLVEPNP_ITERATIVE'
  pnp_ransac_threshold: 5.0  # 放宽要求
  pnp_min_inliers: 8
  pnp_max_iterations: 500
  pnp_confidence: 0.95
  use_stereo_constraints: false

# 可视化配置
visualization_config:
  window_size: [800, 600]
  show_trajectory: true
  show_pointcloud: false  # 简化显示
  max_trajectory_points: 100

# 性能目标（降低要求）
performance_targets:
  target_fps: 10
  max_memory_gb: 4
  max_gpu_memory_gb: 2

# 质量控制（降低要求）
quality_control:
  min_tracking_confidence: 0.1
  max_reprojection_error: 10.0
  tracking_lost_recovery: true
  loop_closure_detection: false